packages:
  - apps/*
allowBuilds:
  argon2: true
  esbuild: true
  sharp: true
minimumReleaseAge: 1440
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - argon2
  - esbuild
  - sharp
verifyDepsBeforeRun: false
